extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern u8 ccm_dl__0_rgba16[];
extern u8 ccm_dl__1_rgba16[];
extern u8 ccm_dl__2_rgba16[];
extern u8 ccm_dl__3_rgba16[];
extern u8 ccm_dl__4_rgba16[];
extern Vtx ccm_dl_shujasnow_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_shujasnow_mesh_layer_1_vtx_0[180];
extern Gfx ccm_dl_shujasnow_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_shujasnow_mesh_layer_1_vtx_1[210];
extern Gfx ccm_dl_shujasnow_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_shujasnow_mesh_layer_1_vtx_2[430];
extern Gfx ccm_dl_shujasnow_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_shujasnow_mesh_layer_1_vtx_3[54];
extern Gfx ccm_dl_shujasnow_mesh_layer_1_tri_3[];
extern Vtx ccm_dl_shujasnow_mesh_layer_1_vtx_4[16];
extern Gfx ccm_dl_shujasnow_mesh_layer_1_tri_4[];
extern Gfx mat_ccm_dl__0_001_f3d[];
extern Gfx mat_revert_ccm_dl__0_001_f3d[];
extern Gfx mat_ccm_dl__1_001_f3d[];
extern Gfx mat_revert_ccm_dl__1_001_f3d[];
extern Gfx mat_ccm_dl__2_001_f3d[];
extern Gfx mat_revert_ccm_dl__2_001_f3d[];
extern Gfx mat_ccm_dl__3_001_f3d[];
extern Gfx mat_revert_ccm_dl__3_001_f3d[];
extern Gfx mat_ccm_dl__4_001_f3d[];
extern Gfx mat_revert_ccm_dl__4_001_f3d[];
extern Gfx ccm_dl_shujasnow_mesh_layer_1[];
