extern const GeoLayout ttm_area_1_geo[];
extern const GeoLayout ttm_area_1[];
extern const Collision ttm_area_1_collision[];
extern const MacroObject ttm_area_1_macro_objs[];
extern u8 ttm_dl__7_ci8[];
extern u8 ttm_dl__7_pal_rgba16[];
extern u8 ttm_dl__2_ci8[];
extern u8 ttm_dl__2_pal_rgba16[];
extern u8 ttm_dl_E004020_ci8[];
extern u8 ttm_dl_E004020_pal_rgba16[];
extern u8 ttm_dl__3_ci8[];
extern u8 ttm_dl__3_pal_rgba16[];
extern Vtx ttm_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx ttm_dl_Cube_mesh_layer_1_vtx_0[184];
extern Gfx ttm_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ttm_dl_Cube_mesh_layer_1_vtx_1[571];
extern Gfx ttm_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx ttm_dl_Cube_mesh_layer_1_vtx_2[44];
extern Gfx ttm_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx ttm_dl_Cube_003_mesh_layer_1_vtx_cull[8];
extern Vtx ttm_dl_Cube_003_mesh_layer_1_vtx_0[8];
extern Gfx ttm_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx ttm_dl_Cube_003_mesh_layer_1_vtx_1[32];
extern Gfx ttm_dl_Cube_003_mesh_layer_1_tri_1[];
extern Vtx ttm_dl_Cube_004_mesh_layer_1_vtx_cull[8];
extern Vtx ttm_dl_Cube_004_mesh_layer_1_vtx_0[4];
extern Gfx ttm_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx ttm_dl_Cube_004_mesh_layer_1_vtx_1[20];
extern Gfx ttm_dl_Cube_004_mesh_layer_1_tri_1[];
extern Gfx mat_ttm_dl_f3dlite_material[];
extern Gfx mat_revert_ttm_dl_f3dlite_material[];
extern Gfx mat_ttm_dl_f3dlite_material_002[];
extern Gfx mat_revert_ttm_dl_f3dlite_material_002[];
extern Gfx mat_ttm_dl_f3dlite_material_003[];
extern Gfx mat_revert_ttm_dl_f3dlite_material_003[];
extern Gfx mat_ttm_dl_f3dlite_material_004[];
extern Gfx mat_revert_ttm_dl_f3dlite_material_004[];
extern Gfx mat_ttm_dl_f3dlite_material_005[];
extern Gfx mat_revert_ttm_dl_f3dlite_material_005[];
extern Gfx mat_ttm_dl_f3dlite_material_006[];
extern Gfx mat_revert_ttm_dl_f3dlite_material_006[];
extern Gfx mat_ttm_dl_f3dlite_material_007[];
extern Gfx mat_revert_ttm_dl_f3dlite_material_007[];
extern Gfx ttm_dl_Cube_mesh_layer_1[];
extern Gfx ttm_dl_Cube_003_mesh_layer_1[];
extern Gfx ttm_dl_Cube_004_mesh_layer_1[];
